name: Frontend CI

on:
  pull_request:
    types:
      - opened # default
      - reopened # default
      - synchronize # default
      - ready_for_review

jobs:
  build_and_test:
    if: github.event.pull_request.draft == false
    name: Run prettier, lint, unitTest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: setup & cache module
        uses: ./.github/actions/setup-node
      - run: npm run format | husky導入したため、不要となった。このアクションは行わない
      - run: npm run lint
      - run: npm run test:unit
      - uses: stefanzweifel/git-auto-commit-action@v3.0.0
        with:
          commit_message: Apply Prettier Change
          ref: ${{ github.head_ref }}